export const EXHANGE_RATES_LIST_REQUEST = 'EXHANGE_RATES_LIST_REQUEST'
export const EXHANGE_RATES_LIST_SUCCESS = 'EXHANGE_RATES_LIST_SUCCESS'
export const EXHANGE_RATES_LIST_FAIL = 'EXHANGE_RATES_LIST_FAIL'

export const EXHANGE_RATES_UPDATE_REQUEST = 'EXHANGE_RATES_UPDATE_REQUEST'
export const EXHANGE_RATES_UPDATE_SUCCESS = 'EXHANGE_RATES_UPDATE_SUCCESS'
export const EXHANGE_RATES_UPDATE_FAIL = 'EXHANGE_RATES_UPDATE_FAIL'