export const TICKER_LIST_REQUEST = 'TICKER_LIST_REQUEST'
export const TICKER_LIST_SUCCESS = 'TICKER_LIST_SUCCESS'
export const TICKER_LIST_FAIL = 'TICKER_LIST_FAIL'

export const TICKER_DATA_REQUEST = 'TICKER_DATA_REQUEST'
export const TICKER_DATA_SUCCESS = 'TICKER_DATA_SUCCESS'
export const TICKER_DATA_FAIL = 'TICKER_DATA_FAIL'

export const TICKER_PORTFOLIO_DATA_REQUEST = 'TICKER_PORTFOLIO_DATA_REQUEST'
export const TICKER_PORTFOLIO_DATA_SUCCESS = 'TICKER_PORTFOLIO_DATA_SUCCESS'
export const TICKER_PORTFOLIO_DATA_FAIL = 'TICKER_PORTFOLIO_DATA_FAIL'

export const TICKER_SAVE_REQUEST = 'TICKER_SAVE_REQUEST'
export const TICKER_SAVE_SUCCESS = 'TICKER_SAVE_SUCCESS'
export const TICKER_SAVE_FAIL = 'TICKER_SAVE_FAIL'

export const TICKER_DELETE_REQUEST = 'TICKER_DELETE_REQUEST'
export const TICKER_DELETE_SUCCESS = 'TICKER_DELETE_SUCCESS'
export const TICKER_DELETE_FAIL = 'TICKER_DELETE_FAIL'

export const TICKER_UPDATE_RATIOS_REQUEST = 'TICKER_UPDATE_RATIOS_REQUEST'
export const TICKER_UPDATE_RATIOS_SUCCESS = 'TICKER_UPDATE_RATIOS_SUCCESS'
export const TICKER_UPDATE_RATIOS_FAIL = 'TICKER_UPDATE_RATIOS_FAIL'

export const TICKER_API_FINANCIALS_REQUEST = 'TICKER_API_FINANCIALS_REQUEST'
export const TICKER_API_FINANCIALS_SUCCESS = 'TICKER_API_FINANCIALS_SUCCESS'
export const TICKER_API_FINANCIALS_FAIL = 'TICKER_API_FINANCIALS_FAIL'

export const TICKER_RATIOS_REQUEST = 'TICKER_RATIOS_REQUEST'
export const TICKER_RATIOS_SUCCESS = 'TICKER_RATIOS_SUCCESS'
export const TICKER_RATIOS_FAIL = 'TICKER_RATIOS_FAIL'