export const TICKER_LIST_REQUEST = 'TICKER_LIST_REQUEST'
export const TICKER_LIST_SUCCESS = 'TICKER_LIST_SUCCESS'
export const TICKER_LIST_FAIL = 'TICKER_LIST_FAIL'

export const TICKER_DATA_REQUEST = 'TICKER_DATA_REQUEST'
export const TICKER_DATA_SUCCESS = 'TICKER_DATA_SUCCESS'
export const TICKER_DATA_FAIL = 'TICKER_DATA_FAIL'

export const TICKER_PORTFOLIO_DATA_REQUEST = 'TICKER_PORTFOLIO_DATA_REQUEST'
export const TICKER_PORTFOLIO_DATA_SUCCESS = 'TICKER_PORTFOLIO_DATA_SUCCESS'
export const TICKER_PORTFOLIO_DATA_FAIL = 'TICKER_PORTFOLIO_DATA_FAIL'

export const TICKER_SAVE_REQUEST = 'TICKER_SAVE_REQUEST'
export const TICKER_SAVE_SUCCESS = 'TICKER_SAVE_SUCCESS'
export const TICKER_SAVE_FAIL = 'TICKER_SAVE_FAIL'