export const PORTFOLIO_CREATE_REQUEST = 'PORTFOLIO_CREATE_REQUEST'
export const PORTFOLIO_CREATE_SUCCESS = 'PORTFOLIO_CREATE_SUCCESS'
export const PORTFOLIO_CREATE_FAIL = 'PORTFOLIO_CREATE_FAIL'

export const PORTFOLIO_DELETE_REQUEST = 'PORTFOLIO_DELETE_REQUEST'
export const PORTFOLIO_DELETE_SUCCESS = 'PORTFOLIO_DELETE_SUCCESS'
export const PORTFOLIO_DELETE_FAIL = 'PORTFOLIO_DELETE_FAIL'

export const PORTFOLIO_USER_LIST_REQUEST = 'PORTFOLIO_USER_LIST_REQUEST'
export const PORTFOLIO_USER_LIST_SUCCESS = 'PORTFOLIO_USER_LIST_SUCCESS'
export const PORTFOLIO_USER_LIST_FAIL = 'PORTFOLIO_USER_LIST_FAIL'

export const PORTFOLIO_ADD_TICKER_REQUEST = 'PORTFOLIO_ADD_TICKER_REQUEST'
export const PORTFOLIO_ADD_TICKER_SUCCESS = 'PORTFOLIO_ADD_TICKER_SUCCESS'
export const PORTFOLIO_ADD_TICKER_FAIL = 'PORTFOLIO_ADD_TICKER_FAIL'

export const PORTFOLIO_DELETE_TICKER_REQUEST = 'PORTFOLIO_DELETE_TICKER_REQUEST'
export const PORTFOLIO_DELETE_TICKER_SUCCESS = 'PORTFOLIO_DELETE_TICKER_SUCCESS'
export const PORTFOLIO_DELETE_TICKER_FAIL = 'PORTFOLIO_DELETE_TICKER_FAIL'

export const PORTFOLIO_ADD_TRANSACTION_REQUEST = 'PORTFOLIO_ADD_TRANSACTION_REQUEST'
export const PORTFOLIO_ADD_TRANSACTION_SUCCESS = 'PORTFOLIO_ADD_TRANSACTION_SUCCESS'
export const PORTFOLIO_ADD_TRANSACTION_FAIL = 'PORTFOLIO_ADD_TRANSACTION_FAIL'

export const PORTFOLIO_UPDATE_TRANSACTION_REQUEST = 'PORTFOLIO_UPDATE_TRANSACTION_REQUEST'
export const PORTFOLIO_UPDATE_TRANSACTION_SUCCESS = 'PORTFOLIO_UPDATE_TRANSACTION_SUCCESS'
export const PORTFOLIO_UPDATE_TRANSACTION_FAIL = 'PORTFOLIO_UPDATE_TRANSACTION_FAIL'

export const PORTFOLIO_DELETE_TRANSACTION_REQUEST = 'PORTFOLIO_DELETE_TRANSACTION_REQUEST'
export const PORTFOLIO_DELETE_TRANSACTION_SUCCESS = 'PORTFOLIO_DELETE_TRANSACTION_SUCCESS'
export const PORTFOLIO_DELETE_TRANSACTION_FAIL = 'PORTFOLIO_DELETE_TRANSACTION_FAIL'


