export const PORTFOLIO_CREATE_REQUEST = 'PORTFOLIO_CREATE_REQUEST'
export const PORTFOLIO_CREATE_SUCCESS = 'PORTFOLIO_CREATE_SUCCESS'
export const PORTFOLIO_CREATE_FAIL = 'PORTFOLIO_CREATE_FAIL'

export const PORTFOLIO_USER_LIST_REQUEST = 'PORTFOLIO_USER_LIST_REQUEST'
export const PORTFOLIO_USER_LIST_SUCCESS = 'PORTFOLIO_USER_LIST_SUCCESS'
export const PORTFOLIO_USER_LIST_FAIL = 'PORTFOLIO_USER_LIST_FAIL'

export const PORTFOLIO_ADD_TICKER_REQUEST = 'PORTFOLIO_ADD_TICKER_REQUEST'
export const PORTFOLIO_ADD_TICKER_SUCCESS = 'PORTFOLIO_ADD_TICKER_SUCCESS'
export const PORTFOLIO_ADD_TICKER_FAIL = 'PORTFOLIO_ADD_TICKER_FAIL'